### ISSUE TITLE
Mac端打开一直显示正在解压，没办法打开

### ISSUE THREAD

**Issue by tuyicha** [Jarvay/desktop48#24]

**Comment by irishwang89** [comment]
你解决了吗?？

**Comment by billjyc** [comment]
+1
![image](https://user-images.githubusercontent.com/4524948/76166752-e18a8c00-619b-11ea-88d0-4fdcb09d14c6.png)

**Comment by tuyicha** [comment]
没有，还是正在解压




在2020年03月09日 00:21，billjyc 写道：

+1

**Comment by tuyicha** [comment]
> 你解决了吗?？

没有

**Comment by irishwang89** [comment]
windows的可以用，我电脑装了Windows虚拟机...

**Comment by Jarvay** [comment]
更新了2.1.6版本，可以手动设置ffmpeg目录

**Comment by billjyc** [comment]
> 更新了2.1.6版本，可以手动设置ffmpeg目录

现在可以进去了，但是在直播的时候，10分钟左右就会自动退出，得重新打开（录播正常）
