### ISSUE TITLE
win端报了个错误，我打不开

### ISSUE THREAD

**Issue by bycen** [Jarvay/desktop48#6]
![Snipaste_2019-04-30_09-32-37](https://user-images.githubusercontent.com/41324481/56936661-3779b680-6b2b-11e9-9f5f-1c99a86e51bf.png)

**Comment by Jarvay** [comment]
刚更新了下，有问题请继续反馈

**Comment by bycen** [comment]
还是报的同样的错误，还是我点错了文件？
![Snipaste_2019-04-30_17-57-27](https://user-images.githubusercontent.com/41324481/56954485-76325f80-6b71-11e9-953b-106ae4918d68.png)

**Comment by Jarvay** [comment]
@bycen sorry，日常“我本地没问题的啊”，等等我再更新下

**Comment by bycen** [comment]
多谢，能够使用了。
有计划添加按团体选择回放么。
![Snipaste_2019-05-01_05-59-18](https://user-images.githubusercontent.com/41324481/56996235-70229a00-6bd6-11e9-8e83-1b93d57ebb02.png)

**Comment by Jarvay** [comment]
@bycen 新版添加了分团筛选功能

**Comment by bycen** [comment]
网页分辨率自适应有计划搞么
这是个回放页面，打开的时候右上角提示“弹幕已连接”，中间一直显示未连接。
右边划不过去，页面也无法缩小（在实际使用上其实并没有影响
现在没便携版了，更新的时候都是覆盖安装么。
聚聚房间第二屏的消息显示逻辑与口袋软件相反（如果是这样设计的，在使用上没有影响
![Snipaste_2019-05-05_20-59-53](https://user-images.githubusercontent.com/41324481/57194480-f4c83c00-6f79-11e9-91b0-70f6160800eb.png)

**Comment by bycen** [comment]
@Jarvay 这个问题已经关闭了，不知道你会不会收到推送，艾特一下。

**Comment by Jarvay** [comment]
1. 其实这个已经是自适应的，但是目前有两个地方出问题，一个是直播（回放）列表的图片大小，第二个就是弹幕这里，我研究一下，实在不行的话会换成口袋那种列表形式
2. 弹幕未连接这个是针对直播的，回放显示的文字会调整下
3. 覆盖就可以了，要是哪天打开直播（回放）列表是空的，可以先尝试在设置更新一下成员信息
4. 房间部分设计就是这样的，按口袋那样感觉有点难
5. 桌面图标下个版本会加上去

**Comment by bycen** [comment]
聚聚房间里右边的成员名单处刷不出来成员名字
